title: Walid Medani # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Fundamentals
  <br><br>
  DACSS 601 - Meredith Rolfe
  <br><br>
  <a href="https://www.linkedin.com/in/wmedani/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
